
                  #####lIST OF OUTFIT COLORS FOR MAIN.PY TO PULL FROM#####





black_outfits = [
  {
    'color': 'Black',
    'name' : 'The "Black N Silver" outfit: ',
    'headwear' : [' ~     N/A'],
    'glass' : ['o-o    Aviator sunglasses (green tint) or silver aviators'],
    'shirt' : ['-|-    Black & Silver Nike T-shirt (Add shirt-stays)'], 
    'belt' : [' =     Black Dress Belt'],
    'pant' : ['/ \    Black chino or black corduroy pants '],
    'footwear' : [' L     Doc Martins + black socks '], 
  },
   {
    'color': 'Black',
    'name' : 'The "Ameba" outfit: ',
    'headwear' : [' ~     N/A'],
    'glass' : ['o-o    Aviator sunglasses  or browline glasses'],
    'shirt' : ['-|-    Black Ameba T-shirt (Add shirt-stays)'], 
    'belt' : [' =     Black ROTC Belt with brass buckle'],
    'pant' : ['/ \    Light blue chinos '],
    'footwear' : [' L     Doc Martins + black socks '], 
  },
   {
    'color': 'Black',
    'name' : 'The "Business Reds" outfit: ',
    'headwear' : [' ~     N/A'],
    'glass' : ['o-o    Browline glasses'],
    'shirt' : ['-|-    Black Polo Dress shirt (Add shirt-stays)'], 
    'belt' : [' =     Black dress belt'],
    'pant' : ['/ \    Red corduroy dress pants '],
    'footwear' : [' L     Doc Martins + black socks '], 
  },
   {
    'color': 'Black',
    'name' : 'The "Unlabled" outfit: ',
    'headwear' : [' ~     Grey Hat'],
    'glass' : ['o-o    None or Browline glasses'],
    'shirt' : ['-|-    Black T-shirt'], 
    'belt' : [' =     Black dress belt'],
    'pant' : ['/ \    Camel corduroy pants '],
    'footwear' : [' L     Doc Martins + black socks '], 
  },
   {
    'color': 'Black',
    'name' : 'The "Snow & Coal" outfit: ',
    'headwear' : [' ~     N/A'],
    'glass' : ['o-o    Browline sunglassesglasses'],
    'shirt' : ['-|-    White shirt (keywest) T-shirt'], 
    'belt' : [' =     Black dress belt'],
    'pant' : ['/ \    Black Thin-lined corduroy pants or Black chinos '],
    'footwear' : [' L     Doc Martins + black socks '], 
  },
    {
    'color': 'Black',
    'name' : 'The "DESTROY-BOYS" outfit: ',
    'headwear' : [' ~     N/A'],
    'glass' : ['o-o    Browline sunglassesglasses'],
    'shirt' : ['-|-    White Destroy Boys shirt T-shirt'], 
    'belt' : [' =     Black dress belt'],
    'pant' : ['/ \     Black chinos or Black Jeans '],
    'footwear' : [' L     Doc Martins or Blac shoes + white or black socks '], 
  },
    {
    'color': 'Black',
    'name' : 'The "Sleek Streetwear" Look: ',
    'headwear' : [' ~     Snapback cap with logo'],
    'glass' : ['o-o    Round mirrored sunglasses'],
    'shirt' : ['-|-    Black graphic print hoodie'], 
    'belt' : [' =     Embossed leather belt'],
    'pant' : ['/ \    Ripped black skinny jeans'],
    'footwear' : [' L     High-top sneakers'], 
  },
  {
    'color': 'Black',
    'name' : 'The "Dark Urbanite" Ensemble: ',
    'headwear' : [' ~     Wide-brimmed black fedora'],
    'glass' : ['o-o    Square-framed dark shades'],
    'shirt' : ['-|-    Charcoal gray turtleneck'], 
    'belt' : [' =     Black leather belt with silver buckle'],
    'pant' : ['/ \    Black slim-fit trousers'],
    'footwear' : [' L     Chelsea boots'], 
  },
  {
    'color': 'Black',
    'name' : 'The "Edgy Elegance" Look: ',
    'headwear' : [' ~     Black leather beret'],
    'glass' : ['o-o    Angular modern sunglasses'],
    'shirt' : ['-|-    Black silk button-up shirt'], 
    'belt' : [' =     Studded leather belt'],
    'pant' : ['/ \    Faux leather skinny pants'],
    'footwear' : [' L     Black combat boots'], 
  },
  {
    'color': 'Black',
    'name' : 'The "Minimal Monochrome" Outfit: ',
    'headwear' : [' ~     Black beanie'],
    'glass' : ['o-o    Classic round frame glasses'],
    'shirt' : ['-|-    Black longline t-shirt'], 
    'belt' : [' =     Matte black belt'],
    'pant' : ['/ \    Black jogger pants'],
    'footwear' : [' L     All-black sneakers'], 
  },
  {
    'color': 'Black',
    'name' : 'The "Nighttime Vibes" Ensemble: ',
    'headwear' : [' ~     Fedora with black ribbon'],
    'glass' : ['o-o    Dark tinted aviator sunglasses'],
    'shirt' : ['-|-    Black button-down shirt'], 
    'belt' : [' =     Woven leather belt'],
    'pant' : ['/ \    Black leather pants'],
    'footwear' : [' L     Black Chelsea boots'], 
  },
  {
    'color': 'Black',
    'name' : 'The "Modern Rebel" Look: ',
    'headwear' : [' ~     Black snapback cap'],
    'glass' : ['o-o    Sleek black wayfarer sunglasses'],
    'shirt' : ['-|-    Distressed black denim jacket'], 
    'belt' : [' =     Studded black belt'],
    'pant' : ['/ \    Faded black skinny jeans'],
    'footwear' : [' L     High-top leather sneakers'], 
  },
  


  
]

########################green#############################

green_outfits = [
  {
    'color': 'Green',
    'name' : 'The "Forrest" outfit: ',
    'headwear' : [' ~     N/A'],
    'glass' : ['o-o    Browline tortoise shell glasses'],
    'shirt' : ['-|-    Black T-shirt '], 
    'belt' : [' =     Black belt with brass buckles'],
    'pant' : ['/ \    Forrest green corduroy pants '],
    'footwear' : [' L     Doc Martins + black socks '], 
    'blank' : [" "],
  },
  {
    'color': 'Green',
    'name' : 'The "Forrest_v3" outfit: ',
    'headwear' : [' ~     N/A'],
    'glass' : ['o-o    Browline tortoise shell glasses'],
    'shirt' : ['-|-    Black T-shirt '], 
    'belt' : [' =     Black belt with brass buckles'],
    'pant' : ['/ \    Forrest green corduroy pants '],
    'footwear' : [' L     Doc Martins + black socks '], 
    'blank' : [" "],
  },
  {
    'color': 'Green',
    'name' : 'The "Forrest_v3" outfit: ',
    'headwear' : [' ~     N/A'],
    'glass' : ['o-o    Browline tortoise shell glasses'],
    'shirt' : ['-|-    Black T-shirt '], 
    'belt' : [' =     Black belt with brass buckles'],
    'pant' : ['/ \    Forrest green corduroy pants '],
    'footwear' : [' L     Doc Martins + black socks '], 
    'blank' : [" "],
  },
    {
    'color': 'Green',
    'name' : 'The "Evergreen" Ensemble: ',
    'headwear' : [' ~     Olive green beanie'],
    'glass' : ['o-o    Round vintage sunglasses'],
    'shirt' : ['-|-    White linen button-up shirt'], 
    'belt' : [' =     Brown leather woven belt'],
    'pant' : ['/ \    Dark khaki slim-fit chinos'],
    'footwear' : [' L     Classic white sneakers'], 
    'blank' : [" "],
  },
  {
    'color': 'Green',
    'name' : 'The "Urban Explorer" Look: ',
    'headwear' : [' ~     Khaki safari hat'],
    'glass' : ['o-o    Aviator sunglasses'],
    'shirt' : ['-|-    Olive green utility shirt'], 
    'belt' : [' =     Black tactical belt'],
    'pant' : ['/ \    Camouflage cargo pants'],
    'footwear' : [' L     Hiking boots'], 
    'blank' : [" "],
  },
  {
    'color': 'Green',
    'name' : 'The "Vintage Vibes" Ensemble: ',
    'headwear' : [' ~     Classic newsboy cap'],
    'glass' : ['o-o    Retro round glasses'],
    'shirt' : ['-|-    Heather green henley shirt'], 
    'belt' : [' =     Distressed brown leather belt'],
    'pant' : ['/ \    Faded olive green jeans'],
    'footwear' : [' L     Brown leather loafers'], 
    'blank' : [" "],
  },
    {
    'color': 'Green',
    'name' : 'The "Vintage Explorer" Look: ',
    'headwear' : [' ~     Weathered leather fedora hat'],
    'glass' : ['o-o    Round polarized sunglasses'],
    'shirt' : ['-|-    Olive green chambray shirt'], 
    'belt' : [' =     Braided brown leather belt'],
    'pant' : ['/ \    Classic khaki cargo shorts'],
    'footwear' : [' L     Suede desert boots'], 
    'blank' : [" "],
  },
  {
    'color': 'Green',
    'name' : 'The "Urban Jungle" Ensemble: ',
    'headwear' : [' ~     Olive green snapback cap'],
    'glass' : ['o-o    Square-framed clear glasses'],
    'shirt' : ['-|-    Black graphic print tee'], 
    'belt' : [' =     Military-style canvas belt'],
    'pant' : ['/ \    Slim-fit forest green joggers'],
    'footwear' : [' L     High-top sneakers'], 
    'blank' : [" "],
  },
  {
    'color': 'Green',
    'name' : 'The "Casual Elegance" Look: ',
    'headwear' : [' ~     Moss green flat cap'],
    'glass' : ['o-o    Tortoise shell rectangular glasses'],
    'shirt' : ['-|-    Crisp white button-down shirt'], 
    'belt' : [' =     Tan leather belt with silver buckle'],
    'pant' : ['/ \    Olive green tailored trousers'],
    'footwear' : [' L     Brown leather dress shoes'], 
    'blank' : [" "],
  },
]

red_outfits = [

{
    'color': 'Red',
    'name' : 'The "Crimson Classic" Look: ',
    'headwear' : [' ~     Red flat cap'],
    'glass' : ['o-o    Round red-tinted sunglasses'],
    'shirt' : ['-|-    Red and white striped sailor tee'], 
    'belt' : [' =     Brown leather belt with brass buckle'],
    'pant' : ['/ \    Navy blue slim-fit chinos'],
    'footwear' : [' L     Boat shoes'], 
  },
  {
    'color': 'Red',
    'name' : 'The "Retro Racer" Ensemble: ',
    'headwear' : [' ~     Red bandana'],
    'glass' : ['o-o    Aviator sunglasses with red mirror lenses'],
    'shirt' : ['-|-    White short-sleeve tee with red logo'], 
    'belt' : [' =     Black leather racing belt'],
    'pant' : ['/ \    Red track pants with white stripes'],
    'footwear' : [' L     Retro-style sneakers'], 
  },
  {
    'color': 'Red',
    'name' : 'The "Casual Comfort" Outfit: ',
    'headwear' : [' ~     Red beanie'],
    'glass' : ['o-o    Classic black wayfarer sunglasses'],
    'shirt' : ['-|-    Heather gray hoodie'], 
    'belt' : [' =     Canvas belt with metal buckle'],
    'pant' : ['/ \    Dark denim jeans'],
    'footwear' : [' L     White low-top sneakers'], 
  },
  {
    'color': 'Red',
    'name' : 'The "Vintage Vibe" Look: ',
    'headwear' : [' ~     Red newsboy cap'],
    'glass' : ['o-o    Round retro-inspired glasses'],
    'shirt' : ['-|-    Red and white varsity jacket'], 
    'belt' : [' =     Brown leather belt with brass accents'],
    'pant' : ['/ \    Light wash denim jeans'],
    'footwear' : [' L     Classic white sneakers'], 
  },
  {
    'color': 'Red',
    'name' : 'The "Chic Downtown" Ensemble: ',
    'headwear' : [' ~     Red fedora hat'],
    'glass' : ['o-o    Square-framed black sunglasses'],
    'shirt' : ['-|-    Black turtleneck sweater'], 
    'belt' : [' =     Black leather belt with silver buckle'],
    'pant' : ['/ \    Charcoal gray wool trousers'],
    'footwear' : [' L     Black leather Chelsea boots'], 
  },
  {
    'color': 'Red',
    'name' : 'The "Statement Streetwear" Look: ',
    'headwear' : [' ~     Red snapback cap'],
    'glass' : ['o-o    Oversized square red sunglasses'],
    'shirt' : ['-|-    Bold red graphic print tee'], 
    'belt' : [' =     Black logo belt'],
    'pant' : ['/ \    Distressed black skinny jeans'],
    'footwear' : [' L     High-top red sneakers'], 
  },
  {
    'color': 'Red',
    'name' : 'The "Urban Explorer" Outfit: ',
    'headwear' : [' ~     Red beanie'],
    'glass' : ['o-o    Sporty wrap-around sunglasses'],
    'shirt' : ['-|-    Red plaid flannel shirt'], 
    'belt' : [' =     Brown leather belt with distressed finish'],
    'pant' : ['/ \    Black cargo pants'],
    'footwear' : [' L     Hiking boots'], 
  },
  {
    'color': 'Red',
    'name' : 'The "Sophisticated Casual" Look: ',
    'headwear' : [' ~     Red knit tie'],
    'glass' : ['o-o    Round tortoise shell glasses'],
    'shirt' : ['-|-    White button-up shirt with red microdots'], 
    'belt' : [' =     Brown leather belt with silver buckle'],
    'pant' : ['/ \    Dark wash straight-leg jeans'],
    'footwear' : [' L     Brown leather loafers'], 
  },
  {
    'color': 'Red',
    'name' : 'The "Sporty Street Style" Ensemble: ',
    'headwear' : [' ~     Red baseball cap'],
    'glass' : ['o-o    Sporty wrap-around sunglasses'],
    'shirt' : ['-|-    Black track jacket with red stripes'], 
    'belt' : [' =     Black nylon belt'],
    'pant' : ['/ \    Black jogger pants'],
    'footwear' : [' L     Red and black sneakers'], 
  },
  {
    'color': 'Red',
    'name' : 'The "Vintage Rugged" Look: ',
    'headwear' : [' ~     Red plaid flat cap'],
    'glass' : ['o-o    Round vintage-style sunglasses'],
    'shirt' : ['-|-    Classic white henley tee'], 
    'belt' : [' =     Brown leather belt with brass buckle'],
    'pant' : ['/ \    Dark wash denim jeans'],
    'footwear' : [' L     Work boots'], 
  }

]

white_outfits = [
  {
    'color': 'White',
    'name' : 'The "Sleek Summer" Look: ',
    'headwear' : [' ~     White baseball cap'],
    'glass' : ['o-o    Square-framed sunglasses'],
    'shirt' : ['-|-    White linen short-sleeve shirt'], 
    'belt' : [' =     Woven brown leather belt'],
    'pant' : ['/ \    Light khaki tailored shorts'],
    'footwear' : [' L     White canvas sneakers'], 
  },
  {
    'color': 'White',
    'name' : 'The "Monochrome Minimalist" Ensemble: ',
    'headwear' : [' ~     White bucket hat'],
    'glass' : ['o-o    Round white-framed sunglasses'],
    'shirt' : ['-|-    White crew-neck tee'], 
    'belt' : [' =     White woven belt'],
    'pant' : ['/ \    White slim-fit jeans'],
    'footwear' : [' L     White low-top sneakers'], 
  },
  {
    'color': 'White',
    'name' : 'The "Casual Cool" Outfit: ',
    'headwear' : [' ~     White dad hat'],
    'glass' : ['o-o    Classic aviator sunglasses'],
    'shirt' : ['-|-    White graphic print hoodie'], 
    'belt' : [' =     Black leather belt with silver buckle'],
    'pant' : ['/ \    Black jogger pants'],
    'footwear' : [' L     Black and white high-top sneakers'], 
  },
  {
    'color': 'White',
    'name' : 'The "Modern Urbanite" Look: ',
    'headwear' : [' ~     White beanie'],
    'glass' : ['o-o    Geometric-framed white sunglasses'],
    'shirt' : ['-|-    White mock neck long-sleeve shirt'], 
    'belt' : [' =     Black webbed belt'],
    'pant' : ['/ \    Dark gray tapered trousers'],
    'footwear' : [' L     Black leather Chelsea boots'], 
  },
  {
    'color': 'White',
    'name' : 'The "Beach Day" Ensemble: ',
    'headwear' : [' ~     White straw fedora'],
    'glass' : ['o-o    Classic round frame sunglasses'],
    'shirt' : ['-|-    White linen button-up shirt'], 
    'belt' : [' =     Braided brown leather belt'],
    'pant' : ['/ \    Light beige tailored shorts'],
    'footwear' : [' L     Brown leather sandals'], 
  },
  {
    'color': 'White',
    'name' : 'The "Modern Monochrome" Look: ',
    'headwear' : [' ~     White snapback cap'],
    'glass' : ['o-o    Angular white-framed sunglasses'],
    'shirt' : ['-|-    White oversized tee'], 
    'belt' : [' =     White canvas belt'],
    'pant' : ['/ \    White jogger pants'],
    'footwear' : [' L     White chunky sneakers'], 
  },
  {
    'color': 'White',
    'name' : 'The "Elegant Evening" Outfit: ',
    'headwear' : [' ~     White silk pocket square'],
    'glass' : ['o-o    Square white-framed glasses'],
    'shirt' : ['-|-    Crisp white dress shirt'], 
    'belt' : [' =     Black leather belt with silver buckle'],
    'pant' : ['/ \    Black tuxedo trousers'],
    'footwear' : [' L     Black patent leather dress shoes'], 
  },
  {
    'color': 'White',
    'name' : 'The "Casual Sophistication" Look: ',
    'headwear' : [' ~     White newsboy cap'],
    'glass' : ['o-o    Retro round frame sunglasses'],
    'shirt' : ['-|-    White textured button-up shirt'], 
    'belt' : [' =     Brown leather belt with brass buckle'],
    'pant' : ['/ \    Navy blue chinos'],
    'footwear' : [' L     Brown leather loafers'], 
  },
  {
    'color': 'White',
    'name' : 'The "Modern Bohemian" Ensemble: ',
    'headwear' : [' ~     White fedora hat'],
    'glass' : ['o-o    Round retro-inspired glasses'],
    'shirt' : ['-|-    Flowy white long-sleeve shirt'], 
    'belt' : [' =     Woven brown leather belt with tassels'],
    'pant' : ['/ \    Light wash denim jeans'],
    'footwear' : [' L     Brown leather sandals'], 
  },
  {
    'color': 'White',
    'name' : 'The "Urban Explorer" Look: ',
    'headwear' : [' ~     White trucker cap'],
    'glass' : ['o-o    Reflective sport sunglasses'],
    'shirt' : ['-|-    White utility jacket'], 
    'belt' : [' =     Black nylon belt'],
    'pant' : ['/ \    Olive green cargo pants'],
    'footwear' : [' L     Hiking boots'], 
  }
]

brown_outfits = [
{
    'color': 'Brown',
    'name' : 'The "Rugged Explorer" Look: ',
    'headwear' : [' ~     Brown wide-brimmed hat'],
    'glass' : ['o-o    Aviator sunglasses'],
    'shirt' : ['-|-    Olive green utility shirt'], 
    'belt' : [' =     Leather belt with brass buckle'],
    'pant' : ['/ \    Dark brown cargo pants'],
    'footwear' : [' L     Brown hiking boots'], 
  },
  {
    'color': 'Brown',
    'name' : 'The "Casual Comfort" Ensemble: ',
    'headwear' : [' ~     Brown beanie'],
    'glass' : ['o-o    Round tortoise shell glasses'],
    'shirt' : ['-|-    Heather gray crew-neck sweater'], 
    'belt' : [' =     Woven brown leather belt'],
    'pant' : ['/ \    Dark blue denim jeans'],
    'footwear' : [' L     Brown leather chukka boots'], 
  },
  {
    'color': 'Brown',
    'name' : 'The "Vintage Charm" Outfit: ',
    'headwear' : [' ~     Brown newsboy cap'],
    'glass' : ['o-o    Classic wayfarer sunglasses'],
    'shirt' : ['-|-    Light brown corduroy jacket'], 
    'belt' : [' =     Brown leather belt with metal accents'],
    'pant' : ['/ \    Dark brown corduroy pants'],
    'footwear' : [' L     Brown leather brogues'], 
  },
  {
    'color': 'Brown',
    'name' : 'The "Casual Elegance" Look: ',
    'headwear' : [' ~     Brown fedora hat'],
    'glass' : ['o-o    Rectangular brown sunglasses'],
    'shirt' : ['-|-    White linen button-up shirt'], 
    'belt' : [' =     Brown leather woven belt'],
    'pant' : ['/ \    Navy blue tailored trousers'],
    'footwear' : [' L     Brown leather loafers'], 
  },
  {
    'color': 'Brown',
    'name' : 'The "Modern Minimalist" Ensemble: ',
    'headwear' : [' ~     Brown flat cap'],
    'glass' : ['o-o    Round gold-framed sunglasses'],
    'shirt' : ['-|-    Black turtleneck sweater'], 
    'belt' : [' =     Brown leather belt with silver buckle'],
    'pant' : ['/ \    Charcoal gray tailored pants'],
    'footwear' : [' L     Brown leather Chelsea boots'], 
  },
  {
    'color': 'Brown',
    'name' : 'The "Vintage Cowboy" Outfit: ',
    'headwear' : [' ~     Brown cowboy hat'],
    'glass' : ['o-o    Square-framed sunglasses'],
    'shirt' : ['-|-    Red and white checkered flannel shirt'], 
    'belt' : [' =     Tooled leather belt with silver buckle'],
    'pant' : ['/ \    Faded blue denim jeans'],
    'footwear' : [' L     Brown leather cowboy boots'], 
  },
  {
    'color': 'Brown',
    'name' : 'The "Urban Edge" Look: ',
    'headwear' : [' ~     Brown snapback cap'],
    'glass' : ['o-o    Geometric-framed sunglasses'],
    'shirt' : ['-|-    Black bomber jacket'], 
    'belt' : [' =     Black webbed belt'],
    'pant' : ['/ \    Dark gray slim-fit jeans'],
    'footwear' : [' L     Black high-top sneakers'], 
  },
  {
    'color': 'Brown',
    'name' : 'The "Vintage Traveler" Ensemble: ',
    'headwear' : [' ~     Brown leather aviator hat'],
    'glass' : ['o-o    Round vintage-style glasses'],
    'shirt' : ['-|-    Cream-colored henley tee'], 
    'belt' : [' =     Distressed brown leather belt'],
    'pant' : ['/ \    Olive green cargo shorts'],
    'footwear' : [' L     Brown leather sandals'], 
  },
  {
    'color': 'Brown',
    'name' : 'The "Classic Preppy" Look: ',
    'headwear' : [' ~     Brown driving cap'],
    'glass' : ['o-o    Round tortoise shell glasses'],
    'shirt' : ['-|-    Light blue Oxford button-down shirt'], 
    'belt' : [' =     Brown braided leather belt'],
    'pant' : ['/ \    Khaki chinos'],
    'footwear' : [' L     Brown loafers'], 
  },
  {
    'color': 'Brown',
    'name' : 'The "Casual Athlete" Outfit: ',
    'headwear' : [' ~     Brown visor'],
    'glass' : ['o-o    Sporty wrap-around sunglasses'],
    'shirt' : ['-|-    Gray athletic tank top'], 
    'belt' : [' =     Black sports belt'],
    'pant' : ['/ \    Brown jogger shorts'],
    'footwear' : [' L     Running shoes'], 
  }
  
]


blue_outfits = [
  {
    'color': 'Blue',
    'name' : 'The "Nautical Charm" Look: ',
    'headwear' : [' ~     Navy blue captain hat'],
    'glass' : ['o-o    Round polarized sunglasses'],
    'shirt' : ['-|-    Breton striped navy and white tee'], 
    'belt' : [' =     Brown leather woven belt'],
    'pant' : ['/ \    Light beige chino shorts'],
    'footwear' : [' L     Brown boat shoes'], 
  },
  {
    'color': 'Blue',
    'name' : 'The "Cool and Casual" Ensemble: ',
    'headwear' : [' ~     Blue baseball cap'],
    'glass' : ['o-o    Classic aviator sunglasses'],
    'shirt' : ['-|-    Gray crew-neck tee'], 
    'belt' : [' =     Black woven belt'],
    'pant' : ['/ \    Dark blue slim-fit jeans'],
    'footwear' : [' L     White low-top sneakers'], 
  },
  {
    'color': 'Blue',
    'name' : 'The "Denim Delight" Outfit: ',
    'headwear' : [' ~     Blue denim bucket hat'],
    'glass' : ['o-o    Retro round frame sunglasses'],
    'shirt' : ['-|-    White graphic print denim jacket'], 
    'belt' : [' =     Brown leather belt with brass buckle'],
    'pant' : ['/ \    Light wash denim jeans'],
    'footwear' : [' L     Brown leather chukka boots'], 
  },
  {
    'color': 'Blue',
    'name' : 'The "Urban Explorer" Look: ',
    'headwear' : [' ~     Blue snapback cap'],
    'glass' : ['o-o    Geometric-framed sunglasses'],
    'shirt' : ['-|-    Black utility shirt'], 
    'belt' : [' =     Black webbed belt'],
    'pant' : ['/ \    Gray cargo pants'],
    'footwear' : [' L     Black high-top sneakers'], 
  },
  {
    'color': 'Blue',
    'name' : 'The "Retro Cool" Ensemble: ',
    'headwear' : [' ~     Blue newsboy cap'],
    'glass' : ['o-o    Round tortoise shell glasses'],
    'shirt' : ['-|-    Burgundy knit polo shirt'], 
    'belt' : [' =     Brown leather belt with metal accents'],
    'pant' : ['/ \    Light blue relaxed-fit jeans'],
    'footwear' : [' L     White canvas sneakers'], 
  },
  {
    'color': 'Blue',
    'name' : 'The "Elegant Evening" Look: ',
    'headwear' : [' ~     Navy blue silk pocket square'],
    'glass' : ['o-o    Square silver-framed glasses'],
    'shirt' : ['-|-    Crisp white dress shirt'], 
    'belt' : [' =     Black leather belt with silver buckle'],
    'pant' : ['/ \    Black tuxedo trousers'],
    'footwear' : [' L     Black patent leather dress shoes'], 
  },
  {
    'color': 'Blue',
    'name' : 'The "Sartorial Sophistication" Outfit: ',
    'headwear' : [' ~     Navy blue flat cap'],
    'glass' : ['o-o    Angular black-framed sunglasses'],
    'shirt' : ['-|-    Light blue linen button-up shirt'], 
    'belt' : [' =     Brown leather belt with silver buckle'],
    'pant' : ['/ \    Charcoal gray tailored trousers'],
    'footwear' : [' L     Brown leather Oxford shoes'], 
  },
  {
    'color': 'Blue',
    'name' : 'The "Casual Athlete" Look: ',
    'headwear' : [' ~     Navy blue visor'],
    'glass' : ['o-o    Sporty wrap-around sunglasses'],
    'shirt' : ['-|-    Gray athletic tank top'], 
    'belt' : [' =     Black sports belt'],
    'pant' : ['/ \    Navy blue jogger shorts'],
    'footwear' : [' L     Running shoes'], 
  },
  {
    'color': 'Blue',
    'name' : 'The "Chic Downtown" Ensemble: ',
    'headwear' : [' ~     Navy blue beanie'],
    'glass' : ['o-o    Rectangular black sunglasses'],
    'shirt' : ['-|-    Black turtleneck sweater'], 
    'belt' : [' =     Black leather belt with silver buckle'],
    'pant' : ['/ \    Gray wool trousers'],
    'footwear' : [' L     Black leather Chelsea boots'], 
  },
  {
    'color': 'Blue',
    'name' : 'The "Preppy Classics" Outfit: ',
    'headwear' : [' ~     Navy blue driving cap'],
    'glass' : ['o-o    Round tortoise shell glasses'],
    'shirt' : ['-|-    Light blue Oxford button-down shirt'], 
    'belt' : [' =     Brown woven leather belt'],
    'pant' : ['/ \    Khaki chinos'],
    'footwear' : [' L     Brown loafers'], 
  }
]

purple_outfits = [
  {
    'color': 'Purple',
    'name' : 'The "Regal Elegance" Look: ',
    'headwear' : [' ~     Dark purple fedora'],
    'glass' : ['o-o    Round gold-framed sunglasses'],
    'shirt' : ['-|-    Crisp white dress shirt'], 
    'belt' : [' =     Black leather belt with silver buckle'],
    'pant' : ['/ \    Deep purple dress trousers'],
    'footwear' : [' L     Black leather loafers'], 
  },
  {
    'color': 'Purple',
    'name' : 'The "Casual Luxe" Ensemble: ',
    'headwear' : [' ~     Light purple beanie'],
    'glass' : ['o-o    Classic wayfarer sunglasses'],
    'shirt' : ['-|-    Gray V-neck cashmere sweater'], 
    'belt' : [' =     Brown leather woven belt'],
    'pant' : ['/ \    Black slim-fit jeans'],
    'footwear' : [' L     White low-top sneakers'], 
  },
  {
    'color': 'Purple',
    'name' : 'The "Urban Artistic" Outfit: ',
    'headwear' : [' ~     Dark purple beret'],
    'glass' : ['o-o    Round tortoise shell glasses'],
    'shirt' : ['-|-    Graphic print purple and white tee'], 
    'belt' : [' =     Black woven belt'],
    'pant' : ['/ \    Gray cargo jogger pants'],
    'footwear' : [' L     Black high-top sneakers'], 
  },
  {
    'color': 'Purple',
    'name' : 'The "Modern Dandy" Look: ',
    'headwear' : [' ~     Purple velvet bowtie'],
    'glass' : ['o-o    Square-framed black glasses'],
    'shirt' : ['-|-    White dress shirt with purple accents'], 
    'belt' : [' =     Black leather belt with silver buckle'],
    'pant' : ['/ \    Black tailored trousers'],
    'footwear' : [' L     Black patent leather dress shoes'], 
  },
  {
    'color': 'Purple',
    'name' : 'The "Sporty Chic" Ensemble: ',
    'headwear' : [' ~     Purple baseball cap'],
    'glass' : ['o-o    Sporty wrap-around sunglasses'],
    'shirt' : ['-|-    Gray athletic hoodie'], 
    'belt' : [' =     Black sports belt'],
    'pant' : ['/ \    Black jogger pants'],
    'footwear' : [' L     White sneakers'], 
  },
  {
    'color': 'Purple',
    'name' : 'The "Grunge Glam" Look: ',
    'headwear' : [' ~     Purple bandana'],
    'glass' : ['o-o    Rectangular black sunglasses'],
    'shirt' : ['-|-    Oversized black graphic print tee'], 
    'belt' : [' =     Studded black belt'],
    'pant' : ['/ \    Distressed black skinny jeans'],
    'footwear' : [' L     Black combat boots'], 
  },
  {
    'color': 'Purple',
    'name' : 'The "Artistic Expression" Outfit: ',
    'headwear' : [' ~     Purple artist beret'],
    'glass' : ['o-o    Round artistic-style glasses'],
    'shirt' : ['-|-    White painterly print shirt'], 
    'belt' : [' =     Brown woven belt'],
    'pant' : ['/ \    Light gray relaxed-fit pants'],
    'footwear' : [' L     Brown leather sandals'], 
  },
  {
    'color': 'Purple',
    'name' : 'The "Modern Rockstar" Look: ',
    'headwear' : [' ~     Purple leather biker cap'],
    'glass' : ['o-o    Round mirrored sunglasses'],
    'shirt' : ['-|-    Black leather moto jacket'], 
    'belt' : [' =     Studded black belt'],
    'pant' : ['/ \    Black skinny jeans'],
    'footwear' : [' L     Black ankle boots'], 
  },
  {
    'color': 'Purple',
    'name' : 'The "Casual Artist" Ensemble: ',
    'headwear' : [' ~     Light purple snapback cap'],
    'glass' : ['o-o    Round tortoise shell glasses'],
    'shirt' : ['-|-    White graphic print artist tee'], 
    'belt' : [' =     Brown leather woven belt'],
    'pant' : ['/ \    Light blue distressed denim jeans'],
    'footwear' : [' L     White canvas sneakers'], 
  },
  {
    'color': 'Purple',
    'name' : 'The "Elegant Night Out" Look: ',
    'headwear' : [' ~     Dark purple velvet bowtie'],
    'glass' : ['o-o    Angular black-framed sunglasses'],
    'shirt' : ['-|-    Black velvet blazer'], 
    'belt' : [' =     Black leather belt with silver buckle'],
    'pant' : ['/ \    Black dress trousers'],
    'footwear' : [' L     Black patent leather dress shoes'], 
  }
]

grey_outfits = [
  {
    'color': 'Grey',
    'name' : 'The "Modern Monochrome" Look: ',
    'headwear' : [' ~     Grey beanie'],
    'glass' : ['o-o    Round tortoise shell glasses'],
    'shirt' : ['-|-    Grey crew-neck tee'], 
    'belt' : [' =     Black woven belt'],
    'pant' : ['/ \    Charcoal grey slim-fit jeans'],
    'footwear' : [' L     Black high-top sneakers'], 
  },
  {
    'color': 'Grey',
    'name' : 'The "Business Casual" Ensemble: ',
    'headwear' : [' ~     Grey flat cap'],
    'glass' : ['o-o    Square-framed black glasses'],
    'shirt' : ['-|-    White dress shirt'], 
    'belt' : [' =     Black leather belt with silver buckle'],
    'pant' : ['/ \    Light grey tailored trousers'],
    'footwear' : [' L     Black leather oxford shoes'], 
  },
  {
    'color': 'Grey',
    'name' : 'The "Sleek Street Style" Outfit: ',
    'headwear' : [' ~     Grey snapback cap'],
    'glass' : ['o-o    Geometric-framed sunglasses'],
    'shirt' : ['-|-    Black utility jacket'], 
    'belt' : [' =     Black webbed belt'],
    'pant' : ['/ \    Dark grey slim-fit jogger pants'],
    'footwear' : [' L     White sneakers'], 
  },
  {
    'color': 'Grey',
    'name' : 'The "Casual Cool" Look: ',
    'headwear' : [' ~     Grey baseball cap'],
    'glass' : ['o-o    Classic aviator sunglasses'],
    'shirt' : ['-|-    Black graphic print tee'], 
    'belt' : [' =     Black woven belt'],
    'pant' : ['/ \    Faded black denim jeans'],
    'footwear' : [' L     Black combat boots'], 
  },
  {
    'color': 'Grey',
    'name' : 'The "Urban Explorer" Ensemble: ',
    'headwear' : [' ~     Grey fedora'],
    'glass' : ['o-o    Round gold-framed sunglasses'],
    'shirt' : ['-|-    Olive green utility shirt'], 
    'belt' : [' =     Brown leather woven belt'],
    'pant' : ['/ \    Dark grey cargo pants'],
    'footwear' : [' L     Brown hiking boots'], 
  },
  {
    'color': 'Grey',
    'name' : 'The "Casual Chic" Look: ',
    'headwear' : [' ~     Grey newsboy cap'],
    'glass' : ['o-o    Retro round frame sunglasses'],
    'shirt' : ['-|-    White Henley long-sleeve tee'], 
    'belt' : [' =     Brown woven belt'],
    'pant' : ['/ \    Light grey chino pants'],
    'footwear' : [' L     Brown loafers'], 
  },
  {
    'color': 'Grey',
    'name' : 'The "Effortless Elegance" Outfit: ',
    'headwear' : [' ~     Grey wool fedora'],
    'glass' : ['o-o    Angular black-framed sunglasses'],
    'shirt' : ['-|-    Black dress shirt'], 
    'belt' : [' =     Black leather belt with silver buckle'],
    'pant' : ['/ \    Charcoal grey tailored trousers'],
    'footwear' : [' L     Black leather Chelsea boots'], 
  },
  {
    'color': 'Grey',
    'name' : 'The "City Explorer" Look: ',
    'headwear' : [' ~     Grey snapback cap'],
    'glass' : ['o-o    Sporty wrap-around sunglasses'],
    'shirt' : ['-|-    Navy blue utility vest'], 
    'belt' : [' =     Black webbed belt'],
    'pant' : ['/ \    Dark grey cargo shorts'],
    'footwear' : [' L     Black hiking sandals'], 
  },
  {
    'color': 'Grey',
    'name' : 'The "Sophisticated Streetwear" Ensemble: ',
    'headwear' : [' ~     Grey beanie'],
    'glass' : ['o-o    Square-framed black glasses'],
    'shirt' : ['-|-    Graphic print grey and white hoodie'], 
    'belt' : [' =     Black woven belt'],
    'pant' : ['/ \    Black distressed jogger pants'],
    'footwear' : [' L     Black high-top sneakers'], 
  },
  {
    'color': 'Grey',
    'name' : 'The "Classic Cool" Look: ',
    'headwear' : [' ~     Grey fedora'],
    'glass' : ['o-o    Round tortoise shell glasses'],
    'shirt' : ['-|-    White crew-neck tee'], 
    'belt' : [' =     Brown woven belt'],
    'pant' : ['/ \    Dark grey straight-leg jeans'],
    'footwear' : [' L     Brown desert boots'], 
  }
]
yellow_outfits = [
  {
    'color': 'Yellow',
    'name' : 'The "Sunset Vibes" Look: ',
    'headwear' : [' ~     Yellow bucket hat'],
    'glass' : ['o-o    Round gold-framed sunglasses'],
    'shirt' : ['-|-    White graphic print tank top'], 
    'belt' : [' =     Brown woven belt'],
    'pant' : ['/ \    Light wash denim shorts'],
    'footwear' : [' L     White sneakers'], 
  },
  {
    'color': 'Yellow',
    'name' : 'The "Casual Summer" Ensemble: ',
    'headwear' : [' ~     Yellow snapback cap'],
    'glass' : ['o-o    Classic aviator sunglasses'],
    'shirt' : ['-|-    Grey V-neck tee'], 
    'belt' : [' =     Brown woven belt'],
    'pant' : ['/ \    Light beige chino shorts'],
    'footwear' : [' L     Brown leather sandals'], 
  },
  {
    'color': 'Yellow',
    'name' : 'The "Urban Explorer" Outfit: ',
    'headwear' : [' ~     Yellow baseball cap'],
    'glass' : ['o-o    Rectangular black sunglasses'],
    'shirt' : ['-|-    Black utility jacket'], 
    'belt' : [' =     Black webbed belt'],
    'pant' : ['/ \    Grey cargo jogger pants'],
    'footwear' : [' L     Black high-top sneakers'], 
  },
  {
    'color': 'Yellow',
    'name' : 'The "Bright and Bold" Look: ',
    'headwear' : [' ~     Yellow visor'],
    'glass' : ['o-o    Geometric-framed sunglasses'],
    'shirt' : ['-|-    Bright yellow short-sleeve button-up shirt'], 
    'belt' : [' =     Brown leather belt with silver buckle'],
    'pant' : ['/ \    Dark wash denim jeans'],
    'footwear' : [' L     Brown loafers'], 
  },
  {
    'color': 'Yellow',
    'name' : 'The "Casual Cool" Ensemble: ',
    'headwear' : [' ~     Yellow beanie'],
    'glass' : ['o-o    Round tortoise shell glasses'],
    'shirt' : ['-|-    Black graphic print tee'], 
    'belt' : [' =     Black woven belt'],
    'pant' : ['/ \    Faded black skinny jeans'],
    'footwear' : [' L     Black combat boots'], 
  },
  {
    'color': 'Yellow',
    'name' : 'The "Summer Brights" Outfit: ',
    'headwear' : [' ~     Yellow snapback cap'],
    'glass' : ['o-o    Round mirrored sunglasses'],
    'shirt' : ['-|-    Turquoise graphic print tank top'], 
    'belt' : [' =     Black woven belt'],
    'pant' : ['/ \    Light grey shorts'],
    'footwear' : [' L     White sneakers'], 
  },
  {
    'color': 'Yellow',
    'name' : 'The "Casual Athlete" Look: ',
    'headwear' : [' ~     Yellow baseball cap'],
    'glass' : ['o-o    Sporty wrap-around sunglasses'],
    'shirt' : ['-|-    Grey athletic hoodie'], 
    'belt' : [' =     Black sports belt'],
    'pant' : ['/ \    Black jogger pants'],
    'footwear' : [' L     Running shoes'], 
  },
  {
    'color': 'Yellow',
    'name' : 'The "Modern Urban" Ensemble: ',
    'headwear' : [' ~     Yellow snapback cap'],
    'glass' : ['o-o    Geometric-framed sunglasses'],
    'shirt' : ['-|-    Black oversized graphic print tee'], 
    'belt' : [' =     Black webbed belt'],
    'pant' : ['/ \    Light wash denim jeans'],
    'footwear' : [' L     White high-top sneakers'], 
  },
  {
    'color': 'Yellow',
    'name' : 'The "Beach Day" Look: ',
    'headwear' : [' ~     Yellow bucket hat'],
    'glass' : ['o-o    Classic wayfarer sunglasses'],
    'shirt' : ['-|-    Striped yellow and white short-sleeve shirt'], 
    'belt' : [' =     Brown woven belt'],
    'pant' : ['/ \    Beige tailored shorts'],
    'footwear' : [' L     Brown leather sandals'], 
  },
  {
    'color': 'Yellow',
    'name' : 'The "Modern Explorer" Outfit: ',
    'headwear' : [' ~     Yellow flat cap'],
    'glass' : ['o-o    Round tortoise shell glasses'],
    'shirt' : ['-|-    Olive green utility shirt'], 
    'belt' : [' =     Brown leather woven belt'],
    'pant' : ['/ \    Grey cargo pants'],
    'footwear' : [' L     Brown hiking boots'], 
  }
]
